version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: docker build -t myappp .
          command: docker run -itd -p 8081:8081 --name myapp-containerr myappp
      - run:
          name: Checking images
          command: docker images

  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Run Tests
          command: echo "Running tests"

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - setup_remote_docker
      - run:
          name: Run Docker Container
          command: docker run -itd -p 8082:8082 --name myapp-containerr myappp

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
